-- H5协议管理系统数据库初始化脚本

-- 创建数据库
CREATE DATABASE IF NOT EXISTS h5_protocol_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE h5_protocol_db;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'viewer' COMMENT 'admin, editor, viewer',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '用户是否启用',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 协议文件表
CREATE TABLE IF NOT EXISTS protocols (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL UNIQUE COMMENT '协议文件名（唯一）',
    description TEXT COMMENT '文件描述',
    app_type VARCHAR(100) COMMENT '应用类型：影视小程序、漫剧小程序、短剧小程序、车机、H5小说',
    app_name VARCHAR(100) COMMENT '应用名称：风行视频小程序、车机等',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_filename (filename),
    INDEX idx_app_type (app_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 操作日志表
CREATE TABLE IF NOT EXISTS operation_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    action VARCHAR(50) NOT NULL COMMENT 'create_protocol, delete_protocol, etc.',
    resource_type VARCHAR(50) NOT NULL COMMENT 'protocol, git',
    resource_name VARCHAR(255),
    details TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 插入默认管理员账户 (用户名: admin@fun.tv, 密码: ******)
INSERT INTO users (username, password_hash, role, is_active)
VALUES ('admin@fun.tv', 'scrypt:32768:8:1$6iUrzTnMUgSM1W89$60be143ffa7402e9f392a39e9c0ca0a69fd2be8cb5c38b8895ace678d5001eff92b5083594740246b46b1c8616b72df65e38c551a6465d13cf2066a829e5cc04', 'admin', TRUE)
ON DUPLICATE KEY UPDATE username=username;

-- 协议文件数据插入SQL
INSERT INTO protocols (filename, description, app_type, app_name) VALUES
('carplay_privacy_api.html', '第三方API个人信息保护政策说明', '车机', '享看视频'),
('carplay_privacy_protocol.html', '隐私协议', '车机', '享看视频'),
('carplay_privacy_sdk.html', '第三方SDK个人信息保护政策说明', '车机', '享看视频'),
('carplay_user_protocol.html', '用户协议', '车机', '享看视频'),
('cheng_about.html', '用户协议', '影视小程序', '橙视频'),
('cheng_privacy.html', '隐私协议', '影视小程序', '橙视频'),
('cheng_vod_agreement.html', '付费服务协议', '影视小程序', '橙视频'),
('cheng_qingxiang_about.html', '用户协议', '影视小程序', '橙橙视频轻享版'),
('cheng_qingxiang_privacy.html', '隐私协议', '影视小程序', '橙橙视频轻享版'),
('cheng_qingxiang_vod_agreement.html', '付费服务协议', '影视小程序', '橙橙视频轻享版'),
('cjykd_about.html', '用户协议', '影视小程序', '长江云看点'),
('cjykd_privacy.html', '隐私协议', '影视小程序', '长江云看点'),
('cjykd_usercancel.html', '用户注销协议', '影视小程序', '长江云看点'),
('cjykd_vod_agreement.html', '付费服务协议', '影视小程序', '长江云看点'),
('cjykd_vod_agreement0321.html', '付费服务协议', '影视小程序', '长江云看点'),
('cfjc_about.html', '用户协议', '小程序', '橙风剧场'),
('cfjc_privacy.html', '隐私协议', '小程序', '橙风剧场'),
('cfjc_usercancel.html', '用户注销协议', '小程序', '橙风剧场'),
('cfjc_vod_agreement.html', '付费服务协议', '小程序', '橙风剧场'),
('dasong_about.html', '用户协议', '漫剧小程序', '通用'),
('dasong_privacy.html', '隐私协议', '漫剧小程序', '通用'),
('dasong_usercancel.html', '用户注销协议', '漫剧小程序', '通用'),
('dasong_vod_agreement.html', '付费服务协议', '漫剧小程序', '通用'),
('dj_common_about.html', '用户协议', '短剧小程序', '通用'),
('dj_common_agreement.html', '用户协议', '短剧小程序', '通用'),
('dj_common_privacy.html', '隐私协议', '短剧小程序', '通用'),
('dj_common_usercancel.html', '用户注销协议', '短剧小程序', '通用'),
('dj_common_vodAgreement.html', '付费服务协议', '短剧小程序', '通用'),
('fengzhi_about.html', '用户协议', '影视小程序', '橙橙趣看'),
('fengzhi_privacy.html', '隐私协议', '影视小程序', '橙橙趣看'),
('fengzhi_vod_agreement.html', '付费服务协议', '影视小程序', '橙橙趣看'),
('fhys_about.html', '用户协议', '影视小程序', '风华影视'),
('fhys_privacy.html', '隐私协议', '影视小程序', '风华影视'),
('fhys_usercancel.html', '用户注销协议', '影视小程序', '风华影视'),
('fhys_vod_agreement.html', '付费服务协议', '影视小程序', '风华影视'),
('fhys_vod_agreement0321.html', '付费服务协议', '影视小程序', '风华影视'),
('fxdj_about.html', '用户协议', '短剧小程序', '风行短剧'),
('fxdj_privacy.html', '隐私协议', '短剧小程序', '风行短剧'),
('fxdj_usercancel.html', '用户注销协议', '短剧小程序', '风行短剧'),
('fxdj_vod_agreement.html', '付费服务协议', '短剧小程序', '风行短剧'),
('fxyj_about.html', '用户协议', '短剧小程序', '风行云剧'),
('fxyj_privacy.html', '隐私协议', '短剧小程序', '风行云剧'),
('fxyj_usercancel.html', '用户注销协议', '短剧小程序', '风行云剧'),
('fxyj_vod_agreement.html', '付费服务协议', '短剧小程序', '风行云剧'),
('hs_private.html', '隐私协议', '影视小程序', '华数TV'),
('hs_vod_agreement.html', '付费服务协议', '影视小程序', '华数TV'),
('hzhbxy.html', '零工经济合作伙伴协议', NULL, NULL),
('collect_clues_accredit.html', '个人信息授权与保护声明', NULL, NULL),
('jianghu_about.html', '用户协议', '短剧小程序', '江湖短剧'),
('jianghu_privacy.html', '隐私协议', '短剧小程序', '江湖短剧'),
('jianghu_usercancel.html', '用户注销协议', '短剧小程序', '江湖短剧'),
('jianghu_vod_agreement.html', '付费服务协议', '短剧小程序', '江湖短剧'),
('jzkd_about.html', '用户协议', '影视小程序', '吉智看点'),
('jzkd_privacy.html', '隐私协议', '影视小程序', '吉智看点'),
('jzkd_usercancel.html', '用户注销协议', '影视小程序', '吉智看点'),
('jzkd_vod_agreement.html', '付费服务协议', '影视小程序', '吉智看点'),
('jzkd_vod_agreement0321.html', '付费服务协议', '影视小程序', '吉智看点'),
('ksdj_czfwxy.html', '充值服务协议', '短剧小程序', '桔子小剧场'),
('ksdj_yhfwxy.html', '用户协议', '短剧小程序', '桔子小剧场'),
('ksdj_ysqbhzc.html', '隐私协议', '短剧小程序', '桔子小剧场'),
('lingmao_privacy.html', '隐私协议', '影视小程序', '灵猫故事会'),
('manying_about.html', '用户协议', '漫剧小程序', '漫影剧好看'),
('manying_privacy.html', '隐私协议', '漫剧小程序', '漫影剧好看'),
('manying_usercancel.html', '用户注销协议', '漫剧小程序', '漫影剧好看'),
('manying_vod_agreement.html', '付费服务协议', '漫剧小程序', '漫影剧好看'),
('novel_time_about.htm', '用户协议', '小说APP', '时光故事客户端'),
('novel_time_agreement.htm', '付费服务协议', '小说APP', '时光故事客户端'),
('novel_time_privacy.htm', '隐私协议', '小说APP', '时光故事客户端'),
('novel_time_sdks.htm', 'SDK说明', '小说APP', '时光故事客户端'),
('qiyijuchang_about.html', '用户协议', '小程序', '奇异剧场'),
('qiyijuchang_privacy.html', '隐私协议', '小程序', '奇异剧场'),
('qiyijuchang_usercancel.html', '用户注销协议', '小程序', '奇异剧场'),
('qiyijuchang_vod_agreement.html', '付费服务协议', '小程序', '奇异剧场'),
('renren_about.html', '用户协议', '影视小程序', '多剧视频'),
('renren_privacy.html', '隐私协议', '影视小程序', '多剧视频'),
('renren_vod_agreement.html', '付费服务协议', '影视小程序', '多剧视频'),
('shunHuo_logout.html', '用户注销协议', '漫剧小程序', '画音阁'),
('shunHuo_privacy.html', '隐私协议', '漫剧小程序', '画音阁'),
('shunHuo_user.html', '用户协议', '漫剧小程序', '画音阁'),
('shunHuo_vip.html', '付费服务协议', '漫剧小程序', '画音阁'),
('tt_fengzhi_about.html', '用户协议', '影视小程序', '橙橙视频'),
('tt_fengzhi_privacy.html', '隐私协议', '影视小程序', '橙橙视频'),
('tt_fengzhi_vod_agreement.html', '付费服务协议', '影视小程序', '橙橙视频'),
('video07_about.html', '用户协议', '影视小程序', '微影院'),
('video07_privacy.html', '隐私协议', '影视小程序', '微影院'),
('video07_vod_agreement.html', '付费服务协议', '影视小程序', '微影院'),
('video071_about.html', '用户协议', '影视小程序', '微看点'),
('video071_privacy.html', '隐私协议', '影视小程序', '微看点'),
('video071_vod_agreement.html', '付费服务协议', '影视小程序', '微看点'),
('video072_about.html', '用户协议', '小程序', '微迪趣看'),
('video072_privacy.html', '隐私协议', '小程序', '微迪趣看'),
('video072_vod_agreement.html', '付费服务协议', '小程序', '微迪趣看'),
('weilai_about.html', '用户协议', '影视小程序', '未来看点'),
('weilai_privacy.html', '隐私协议', '影视小程序', '未来看点'),
('weilai_usercancel.html', '用户注销协议', '影视小程序', '未来看点'),
('weilai_vod_agreement.html', '付费服务协议', '影视小程序', '未来看点'),
('wuxian_about.html', '用户协议', '影视小程序', '无限看点'),
('wuxian_privacy.html', '隐私协议', '影视小程序', '无限看点'),
('wuxian_usercancel.html', '用户注销协议', '影视小程序', '无限看点'),
('wuxian_vod_agreement.html', '付费服务协议', '影视小程序', '无限看点'),
('xckd_about.html', '用户协议', '影视小程序', '星橙看点'),
('xckd_privacy.html', '隐私协议', '影视小程序', '星橙看点'),
('xckd_usercancel.html', '用户注销协议', '影视小程序', '星橙看点'),
('xckd_vod_agreement.html', '付费服务协议', '影视小程序', '星橙看点'),
('xcwj_privacy.html', '隐私协议', '小说', '星辰文鉴'),
('xcwj_vod_agreement.html', '付费服务协议', '小说', '星辰文鉴'),
('xgyp_privacy.html', '隐私协议', '影视小程序', '星光影票'),
('xgyy_about.html', '用户协议', '影视小程序', '星光影院'),
('xgyy_privacy.html', '隐私协议', '影视小程序', '星光影院'),
('xgyy_usercancel.html', '用户注销协议', '影视小程序', '星光影院'),
('xgyy_vod_agreement.html', '付费服务协议', '影视小程序', '星光影院'),
('xgyy_vod_agreement0321.html', '付费服务协议', '影视小程序', '星光影院'),
('xiaP_about.html', '用户协议', '影视小程序', '虾皮追剧'),
('xiaP_privacy.html', '隐私协议', '影视小程序', '虾皮追剧'),
('xiaP_vip.html', '付费服务协议', '影视小程序', '虾皮追剧'),
('xyqk_about.html', '用户协议', '影视小程序', '星云趣看'),
('xyqk_privacy.html', '隐私协议', '影视小程序', '星云趣看'),
('xyqk_usercancel.html', '用户注销协议', '影视小程序', '星云趣看'),
('xyqk_vod_agreement.html', '付费服务协议', '影视小程序', '星云趣看'),
('xyys_about.html', '用户协议', '影视小程序', '星合看点'),
('xyys_privacy.html', '隐私协议', '影视小程序', '星合看点'),
('xyys_usercancel.html', '用户注销协议', '影视小程序', '星合看点'),
('xyys_vod_agreement.html', '付费服务协议', '影视小程序', '星合看点'),
('ys_common_about.html', '用户协议', '影视小程序', '通用'),
('ys_common_agreement.html', '用户协议', '影视小程序', '通用'),
('ys_common_privacy.html', '隐私协议', '影视小程序', '通用'),
('ysp_about.html', '用户协议', '影视小程序', 'C位看影视'),
('ysp_agreement.html', '付费服务协议', '影视/小说', '通用'),
('ysp_privacy.html', '隐私协议', '影视小程序', 'C位看影视'),
('yuedu_privacy.html', '用户协议', NULL, '悦读故事会'),
('yst_vip.html', '会员服务协议', NULL, '悦视通'),
('yueshi_about.html', '用户协议', '影视小程序', '悦视通'),
('yueshi_privacy.html', '隐私协议', '影视小程序', '悦视通'),
('yueshi_usercancel.html', '用户注销协议', '影视小程序', '悦视通'),
('yueshi_vod_agreement.html', '付费服务协议', '影视小程序', '悦视通'),
('yueshi_vod_agreement0321.html', '付费服务协议', '影视小程序', '悦视通')
ON DUPLICATE KEY UPDATE
    description=VALUES(description),
    app_type=VALUES(app_type),
    app_name=VALUES(app_name);
